### ISSUE TITLE
Could you offer the data for inferencing your code

### ISSUE THREAD

**Issue by Joe618** [jyunlee/Pop-Out-Motion#3]
Thank you for this great work! I am wondering whether it is possible to release the data for train and test. Your help is greatly appreciated!

**Comment by jyunlee** [comment]
Hello! Do you mean the training and test sets for DFAUST? We are sorry that we cannot directly release these sets due to copyright issues. We downloaded DFAUST dataset from its official website and subsampled the shapes in each sequence by a factor of 16 due to the high frame rate. We then used _50025_ and _50027_ samples for testing, _50026_ samples for validation, and the rest of the samples for training. Let me know if you have more questions!

**Comment by Joe618** [comment]
Thanks a lot for your replying.

But I have the another question needing your help. I met a error which is 
"/root/miniconda3/envs/pop_out/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Error executing job with overrides: []
Traceback (most recent call last):
  File "/root/miniconda3/envs/pop_out/lib/python3.8/site-packages/hydra/_internal/utils.py", line 570, in _locate
    module = import_module(mod)
  File "/root/miniconda3/envs/pop_out/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1011, in _gcd_import
  File "<frozen importlib._bootstrap>", line 950, in _sanity_check
ValueError: Empty module name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "a_inference.py", line 125, in main
    regressor = hydra.utils.instantiate(cfg.task_model, hydra_params_to_dotdict(cfg))
  File "/root/miniconda3/envs/pop_out/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/root/miniconda3/envs/pop_out/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 266, in instantiate_node
    cfg[key] = instantiate_node(
  File "/root/miniconda3/envs/pop_out/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 240, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET))
  File "/root/miniconda3/envs/pop_out/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 104, in _resolve_target
    return _locate(target)
  File "/root/miniconda3/envs/pop_out/lib/python3.8/site-packages/hydra/_internal/utils.py", line 573, in _locate
    raise ImportError(f"Error loading module '{path}'") from e
ImportError: Error loading module 'models.LapNet'"

Do you have some ideas for the error? 

I guess your provided config files in ./network/configs/* have some problems so that I met above errors and cannot reproduce your achievement using your open codes. Could you help me to see if there is any problem with the code you uploaded?

Thank you in advance.
